name: CI

on:
  pull_request:
    branches: [main, dev]
    paths:
     - "packages/react-url-query-params"
     - ".github/workflows/ci.yml"

  push:
    branches: [main, dev]
    paths:
    - "packages/react-url-query-params"
    - ".github/workflows/ci.yml"

env:
  HUSKY: 0

permissions:
  contents: read


jobs:
  test:
    runs-on: "ubuntu@lates"
    strategy:
      matrix:
        node: [18, 20]
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node}}
        cache: npm

    - name: Upgrade npm
      run: |
          npm install -g npm@latest
          npm -v

    - name: Install deps (root)
      working-directory: packages/react-url-query-params
      run: npm install

    - name: Run tests (unit)
      working-directory: packages/react-url-query-params
      run: npm run test:run



